export const ADD_ADDRESS = 'ADD_ADDRESS';
export const START_LOAD_PROFILE = 'START_LOAD_PROFILE';
export const FINISH_LOAD_PROFILE = 'FINISH_LOAD_PROFILE';
export const ERROR_LOAD_PROFILE = 'ERROR_LOAD_PROFILE';

